#!/usr/bin/env bash

function pipe_open() {
  local name="$1"
  [[ -p "$name" ]]
}

function assert_pipe() {
  local name="$1"
  pipe_open "$name" || {
    echo "$name is not a pipe"
    return 1
  }
}

function drip() {
  local name="$1"
  assert_pipe "$name"
  echo "$(<"$name")"
}

function pipe() {
  local name="$1"
  mkfifo "$name"
  create_pump "$name"
  
}

function create_pump() {
  local name="$1"
  eval "$(cat <<EOF
    function $name() {
      #echo in app custom func \$#
      assert_pipe $name &&
      {
        if [ \$# -gt 0 ]; then
          echo "\${@}" | while read -r line; do echo "\$line" >$name; done
        else
          while read -r line; do echo "\$line" >$name; done
        fi
      }
    }
EOF
  )"
}

function rm_pipe() {
  local name="$1"
  assert_pipe "$name" && rm "$name"
  unset -f "$name" # destroy pump
}

function pipe_enable_aliases() {
  shopt -s expand_aliases
}

function pipe_disable_aliases() {
  shopt -u expand_aliases
}