#!/usr/bin/env bash

whereami="${1-.}"
source "$PWD/$whereami/pipe"
unset whereami

# ./pipe only has primitives
# ./protopipe has protocol:
# - shutoff with :close:
# - flow that supports shutoff

function protopipe() {
  local name="$1"
  pipe "$name"
  alias $name...="flow $name"
}

PIPE_SHUTOFF_MSG_=:close:

function flow() {
  local name="$1"
  local handle_msg="$2"
  
  while true; do
    local msg
    msg="$(drip "$name")"
    if [ "$msg" = "$PIPE_SHUTOFF_MSG_" ]; then
      rm_pipe app
      break
    else
      "$handle_msg" "$msg"
    fi
  done
}

function shutoff() {
  local name="$1"
  "$name" <<< "$PIPE_SHUTOFF_MSG_"
}