#!/usr/bin/env bash

source "$(dirname "$0")/../protopipe"
pipe_enable_aliases

rm_pipe app &> /dev/null # just to be safe
protopipe app

function on_msg() {
  echo "app:" "${@}"
}

function on_shutoff() {
  echo bye bye!
}

app... on_msg && on_shutoff &

sleep 2 && app <<< timeout && shutoff app &

app <<< hi

{
  app <<< 1
  app <<< 2

  echo "3
  4" | app
  
  app "5
  6"
  
  echo "7
8" >app
  
  app <<EOL
  9
  10
EOL
  
  sleep 4 && shutoff app
} &

wait
